name: Deploy to EC2

on:
  push:
    branches:
      - main   # Cambia si tu rama principal es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy en EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/pui-api
            git pull origin main
            pm2 restart pui-api || pm2 start server.js --name pui-api
            pm2 save
          EOF
